Q3 part b


In [11]:
import math
import numpy as np
from sklearn.metrics import accuracy_score
w_0 = np.array([0.3,-0.2,0.7]).T
x = np.array([[4,4,1],[6,4,1],[6,5,1],[6,8,1],[6,10,1],[8,8,1],[8,10,1]])
y = np.array([1,1,1,0,0,1,0])
def p(w,x):
    return  1/(1+math.exp(- w.T @ x))

def new_W(oldW,y,y_pred,x):
    sum = 0

    for i in range(len(y)):
        sum += (y[i]-y_pred[i])*x[i].T
    return oldW - 0.01*-1 *sum

#iter 1
y_pred = np.zeros((len(x)))
for i in range(len(x)):
    y_pred[i] = p(w_0,x[i].T)
print(y_pred)
w_1 = new_W(w_0,y,y_pred,x)
print(w_1)
y_pred = np.round(y_pred)

print("accuracy_score:",accuracy_score(y_pred,y))

#iter2
y_pred = np.zeros((len(x)))
for i in range(len(x)):
    y_pred[i] = p(w_1,x[i].T)
print(y_pred)
w_2 = new_W(w_1,y,y_pred,x)
print(w_2)

y_pred = np.round(y_pred)

print("accuracy_score:",accuracy_score(y_pred,y))
#iter3
y_pred = np.zeros((len(x)))
for i in range(len(x)):
    y_pred[i] = p(w_2,x[i].T)
print(y_pred)
w_3 = new_W(w_2,y,y_pred,x)
print(w_3)

y_pred = np.round(y_pred)

print("accuracy_score:",accuracy_score(y_pred,y))
#iter4
y_pred = np.zeros((len(x)))
for i in range(len(x)):
    y_pred[i] = p(w_3,x[i].T)
y_pred = np.round(y_pred)
print(y_pred)
w_4 = new_W(w_3,y,y_pred,x)
print(w_4)
y_pred = np.round(y_pred)

print("accuracy_score:",accuracy_score(y_pred,y))




    


[0.75026011 0.84553473 0.81757448 0.7109495  0.62245933 0.81757448
 0.75026011]
[ 0.20477175 -0.35426438  0.68685387]
accuracy_score: 0.5714285714285714
[0.52220622 0.62208956 0.53597832 0.28523698 0.16421986 0.37540753
 0.22835627]
[ 0.27913091 -0.3089443   0.69951893]
accuracy_score: 0.8571428571428571
[0.64112846 0.75740912 0.69626672 0.47570664 0.32846439 0.61325417
 0.46086103]
[ 0.27208574 -0.35574855  0.69978802]
accuracy_score: 1.0
[1. 1. 1. 0. 0. 1. 0.]
[ 0.27208574 -0.35574855  0.69978802]
accuracy_score: 1.0
